// The same facts for every product, so they can sit side by side on the Compare page.
// From DPY's spec sheets (src/specs.json) and product pages; '' = not stated by DPY (shown as a dash).
// mods: how many models · pw: heating power · cap: tank or capacity · eff: efficiency · temp: hot water · taps: what it serves · sup: power supply
// where: where it goes · dim: size and weight · plus: stand-out features
export const ROWS = [
  ['pw', 'Heating power'], ['eff', 'Running cost'], ['cap', 'Tank / capacity'], ['temp', 'Hot water'], ['taps', 'Serves'],
  ['sup', 'Power supply'], ['where', 'Where it goes'], ['dim', 'Size & weight'], ['mods', 'Models'], ['plus', 'Stand-out features'],
]
const IP = 'Twin thermostats, auto shut-off, IP25 splash-proof'
export const CMP = {
  'aquapower-a35m-a55': { pw: '3.5 or 5.5 kW', eff: 'Heats only what you use', cap: 'No tank: heats as it flows', temp: 'Adjustable', taps: 'Shower + sink (multipoint)', sup: '220 V · 20 or 30 A breaker', where: 'Wall, beside the shower', dim: '100 × 135 × 205 mm · 1.2 kg', mods: '2', plus: `99.9% copper tank · ${IP}` },
  'aquapower-aqp-28n': { pw: '3.5 kW', eff: 'Heats only what you use', cap: 'No tank: heats as it flows', temp: 'Adjustable', taps: 'One shower (singlepoint)', sup: '220 V · 20 A breaker', where: 'Wall, beside the shower', dim: '225 × 75 × 325 mm · 2.35 kg', mods: '1', plus: `Slim black design · tested to 3.5 MPa · ${IP}` },
  'aquapower-q35m': { pw: '3.5 kW', eff: 'Heats only what you use', cap: 'No tank: heats as it flows', temp: 'Adjustable', taps: 'One shower (singlepoint)', sup: '220 V · 20 A breaker', where: 'Wall, beside the shower', dim: '100 × 220 × 300 mm · 1.7 kg', mods: '1', plus: `Comes with a shower set · ${IP}` },
  'aquapower-q6m-q9m': { pw: '6 or 9 kW', eff: 'Heats only what you use', cap: 'No tank: heats as it flows', temp: 'Adjustable', taps: 'Shower + sink (multipoint)', sup: '220 V · 30 or 40 A breaker', where: 'Wall, near the bathroom', dim: '100 × 220 × 300 mm · 1.7 kg', mods: '2', plus: `Most powerful instant heater · ${IP}` },
  'aquapower-s35m-s45m': { pw: '3.5 or 4.5 kW', eff: 'Heats only what you use', cap: 'No tank: heats as it flows', temp: 'Adjustable', taps: 'One shower (singlepoint)', sup: '220 V · 20 or 30 A breaker', where: 'Wall, beside the shower', dim: '100 × 135 × 205 mm · 1.2 kg', mods: '2', plus: `Compact · ${IP}` },
  'gratek-aquarius-aqa-30': { pw: '3.5 or 5.5 kW', eff: 'Heats only what you use', cap: 'No tank: heats as it flows', temp: 'Adjustable', taps: 'One shower (singlepoint)', sup: '220 V · 20 or 30 A breaker', where: 'Wall, beside the shower', dim: '300 × 95 × 185 mm · 1.7 kg', mods: '2', plus: `Built-in booster pump · stainless steel tank · ${IP}` },
  'gratek-aquarius-aqa-30e': { pw: '3.5 or 5.5 kW', eff: 'Heats only what you use', cap: 'No tank: heats as it flows', temp: 'Adjustable flow and temperature', taps: 'Shower + sink (multipoint)', sup: '220 V · 20 or 30 A breaker', where: 'Wall, near the bathroom', dim: '300 × 95 × 185 mm · 1.7 kg', mods: '2', plus: `Built-in booster pump · automatic relief valve · ${IP}` },
  'rheem': { pw: '3 kW (wall) · 4.5–5.5 kW (floor)', eff: 'Standard electric, well insulated', cap: '25–454 liters', temp: 'Preset 60°C, adjustable', taps: 'Several taps at once', sup: '240 V single phase', where: 'Wall (25–100 L) or floor (114–454 L)', dim: '17–36 kg empty (wall models)', mods: '11', plus: 'Glass-lined tank fused at 870°C · UL relief valve · anode rod' },
  'everhot': { pw: '1.5–4.8 kW', eff: 'Standard electric, well insulated', cap: '25–492 liters', temp: 'Adjustable thermostat', taps: 'Several taps at once', sup: '220 V · 15 or 20 A protection', where: 'Wall or floor, indoors or outdoors', dim: '370–681 mm wide · 440–1,911 mm tall', mods: '11', plus: 'Enamel-lined tank · relief valve at 0.85 MPa · anode rod' },
  '5-star-integral-heat-pump': { pw: '2.8 kW of heat from 0.7 kW', eff: 'About 4× an electric heater (COP 4)', cap: '100–300 liters, built in', temp: 'With 1.5 kW backup heater', taps: 'A home or small business', sup: '220–240 V', where: 'Floor: laundry, garage or near the kitchen', dim: '560–640 mm wide · 65–103 kg', mods: '5', plus: 'Cools and dries the room it\'s in · solar coil optional · 47–48 dB' },
  'deron-air-to-water-heat-pump': { pw: '3.4–20 kW of heat', eff: 'About 4× an electric heater (up to 70% saving)', cap: 'Works with a separate storage tank', temp: 'Up to 60°C (over 65°C on request)', taps: 'A whole building', sup: '220 V single phase or 380 V three phase', where: 'Outdoors', dim: '52–110 kg', mods: '7', plus: 'Several compressors per unit · automatic, runs 24 hours · auto defrost' },
  'deron-water-to-water-heat-pump': { pw: '11.5–40 kW of heat', eff: 'COP up to 4.4', cap: 'Works with a 3–10 t tank', temp: 'Up to 60°C', taps: 'A whole building', sup: '380 V three phase', where: 'Indoor plant room', dim: '80–250 kg', mods: '3', plus: 'Heat from ground, lake or river water · also cools (9–30 kW) · quiet, ≤40–44 dB' },
  'deron-swimming-pool-heat-pump': { pw: '34–86 kW of heat', eff: 'About 5.5× an electric heater (in 26°C air)', cap: 'For the pool', temp: 'Pool at 28°C (up to 45°C)', taps: 'A swimming pool', sup: '380 V three phase', where: 'Outdoors, near the pool', dim: '250–622 kg', mods: '5', plus: 'Titanium heat exchanger (chlorine-proof) · also cools · low-noise' },
  '5-star-solar-water-heater': { pw: 'The sun, plus a 2 kW backup', eff: 'Lowest: heated by the sun', cap: '40 or 80 gallons (about 150 or 300 L)', temp: 'Loses under 5°C a day', taps: 'A home or small resort', sup: '220 V for the backup heater', where: 'Roof, in the sun', dim: 'Panel 2,000 × 1,000 mm', mods: '2', plus: 'Absorbs 92–96% of sunlight · full water pressure · split type available' },
  'haase-energy-storage-tank': { pw: 'Stores heat from other sources', eff: '93% storage efficiency', cap: '1,000–40,000 liters', temp: '', taps: 'A whole building', sup: 'None (no heater of its own)', where: 'Plant room, assembled on site', dim: 'Built to fit the room', mods: 'Made to order', plus: 'Clean first-in, first-out hot water · many heat sources · made in Germany' },
  'champion-storage-tank': { pw: 'Stores hot water from heaters', eff: '50 mm fiberglass insulation', cap: '350–2,000 gallons (about 1,300–7,600 L)', temp: 'Designed for up to 220°C', taps: 'A whole building', sup: 'None (no heater of its own)', where: 'Plant room, on three legs', dim: '2,120–3,050 mm tall', mods: '6', plus: '2 mm glass lining · 125 PSI (150 available) · gauges, valves and manhole included' },
  'enermax-storage-tank': { pw: 'Stores heat from other sources', eff: '', cap: '', temp: '', taps: 'A whole building', sup: 'None (no heater of its own)', where: 'Plant room', dim: '', mods: '', plus: 'Several heat sources in, several uses out' },
  'rotex-sanicube': { pw: 'Stores heat from other sources', eff: 'Very low heat loss', cap: 'Modular', temp: '', taps: 'A whole building', sup: 'None (no heater of its own)', where: 'Plant room, modular', dim: '', mods: 'Modular', plus: 'No legionella · can\'t corrode · 50-year engineering life · made in Germany' },
  'wilo-pumps': { pw: '', eff: '', cap: '', temp: '', taps: 'A whole building', sup: '', where: 'Plant room', dim: '', mods: 'Many', plus: 'Circulation and booster pumps, sized by our engineers' },
  'aquaplast-ppr-pipes': { pw: '', eff: '', cap: '', temp: 'Made for hot water', taps: 'Any hot water line', sup: '', where: 'In the walls and ceilings', dim: '', mods: 'Full range', plus: 'Pipes, elbows, couplings and valves · won\'t rust or scale' },
  'my-pv-ac-thor-9s': { pw: 'Up to 3 × 3,000 W', eff: 'Uses spare solar power', cap: '', temp: 'Digital sensor included', taps: 'Your water heater', sup: '1, 2 or 3 phase', where: 'Wall, near the heater', dim: '', mods: '1', plus: 'Smooth 0–9 kW control · 16 A relay' },
  'my-pv-ac-thor-i': { pw: '0–3 kW', eff: 'Uses spare solar power', cap: '', temp: 'Digital sensor included', taps: 'Your water heater', sup: 'Single phase', where: 'Wall, near the heater', dim: '', mods: '1', plus: 'Plug-in output · 16 A relay · stylus and bracket included' },
  'my-pv-power-meter': { pw: '', eff: 'Measures your solar surplus', cap: '', temp: '', taps: 'An AC·THOR', sup: '3 phase', where: 'Your electrical panel', dim: '', mods: '1', plus: 'Three clip-on 60 A sensors, no rewiring' },
  'katen-exhaust-fans': { pw: '', eff: '', cap: '', temp: '', taps: 'Bathroom, kitchen or laundry', sup: '', where: 'Wall or window', dim: '', mods: '3', plus: 'Clears steam and heat' },
}
// quick sets offered on the Compare page
export const SETS = [
  ['Instant heaters', ['aquapower-a35m-a55', 'aquapower-s35m-s45m', 'gratek-aquarius-aqa-30', 'aquapower-q6m-q9m']],
  ['Storage heaters', ['rheem', 'everhot', '5-star-integral-heat-pump']],
  ['Heat pumps', ['5-star-integral-heat-pump', 'deron-air-to-water-heat-pump', 'deron-water-to-water-heat-pump', 'deron-swimming-pool-heat-pump']],
  ['Lowest running cost', ['5-star-solar-water-heater', '5-star-integral-heat-pump', 'deron-air-to-water-heat-pump']],
  ['Storage tanks', ['haase-energy-storage-tank', 'champion-storage-tank', 'rotex-sanicube']],
]
