// Every product DPY and Gratek list on dpymi.com.ph, rewritten in plain English for customers.
// Facts come from the live product pages and DPY's spec sheets (specs.json, typed from the sheet images).
// img: a file in assets/img/dpy (no extension). specs: keys in specs.json.

export const CATS = {
  instant: { t: 'Instant water heaters', s: 'Instant', d: 'Heats water as it flows, so the shower is hot in seconds. Compact, with no tank.', icon: 'bolt' },
  storage: { t: 'Electric storage heaters', s: 'Storage', d: 'Keeps a tank of hot water ready, so several taps can run at once.', icon: 'tank' },
  heatpump: { t: 'Heat pumps', s: 'Heat pump', d: 'Moves warmth from the air into the water, using far less electricity.', icon: 'fan' },
  solar: { t: 'Solar water heaters', s: 'Solar', d: 'Heated by the sun on your roof, with an electric backup for cloudy days.', icon: 'sun' },
  tank: { t: 'Storage tanks', s: 'Tank', d: 'Large hot water tanks for whole buildings, from 350 to 40,000 liters.', icon: 'tank' },
  pump: { t: 'Pumps', s: 'Pump', d: 'Keep hot water moving, so every tap in the building runs hot fast.', icon: 'pump' },
  pipe: { t: 'Pipes & fittings', s: 'Pipes', d: 'Heat-resistant pipes, elbows and valves for hot water lines.', icon: 'pipe' },
  control: { t: 'Solar power control', s: 'Solar control', d: 'Sends spare power from your solar panels into heating water.', icon: 'chip' },
  fan: { t: 'Exhaust fans', s: 'Fan', d: 'Clear steam and heat from bathrooms and kitchens.', icon: 'fan' },
}

// shared feature sets (several Aquapower and Gratek models share one feature list on dpymi.com.ph)
const INSTANT = [
  ['Works on low water pressure', 'It switches on at just 2 liters a minute, so it suits condos and upper floors with weak pressure.'],
  ['No scalding, no overheating', 'Two thermostats cut the power if the water gets too hot, with automatic and manual reset.'],
  ['Shuts itself off when something is wrong', 'A pressure switch turns the heater off if the water flow becomes irregular.'],
  ['Splash-proof', 'Water and dust resistant casing, rated IP25, safe to mount in the shower area.'],
  ['Built to last', 'Tested for over 3,000 hours of continuous use. It can last 30 years with clean water.'],
  ['Compact', 'Small enough to mount beside the shower, or hide out of sight.'],
]
const INSTANT_W = '5 years on the heating element, 1 year on parts'
const AQ_COPPER = ['Fast heating, copper tank', 'The 99.9% copper tank transfers heat quickly and stands up to years of use.']
const AQ_PUMP = ['Built-in booster pump', 'A high-efficiency pump keeps the flow strong even when the water pressure is low.']

export const PRODUCTS = [
  // ---------- instant ----------
  { slug: 'aquapower-a35m-a55', name: 'Aquapower A35M / A55', brand: 'Aquapower', cat: 'instant', sub: 'Multipoint', for: ['home'], img: 'aquapower-a35',
    short: 'A multipoint instant heater: one unit can feed the shower and the sink.',
    key: [['3.5 / 5.5', 'kW'], ['2', 'L/min to start'], ['2+', 'taps']],
    best: ['Bathrooms with a shower and sink', 'Condos', 'Low pressure'],
    feats: [['Serves more than one tap', 'Multipoint: one heater can supply the shower and the bathroom sink together.'], AQ_COPPER, ...INSTANT.slice(0, 5)],
    warranty: INSTANT_W, specs: ['Aquapower-A35M-and-A55'], from: 'product/aquapower-a35m/' },
  { slug: 'aquapower-aqp-28n', name: 'Aquapower AQP-28N', brand: 'Aquapower', cat: 'instant', sub: 'Singlepoint', for: ['home'], img: 'aquapower-aqp28n',
    short: 'A slim single-point heater with a modern black finish, for one shower.',
    key: [['3.5', 'kW'], ['2', 'L/min to start'], ['75', 'mm slim']],
    best: ['One shower', 'Modern bathrooms', 'Small spaces'],
    feats: [['Simple to use', 'Set the power, the water flow and the temperature with two dials.'], ['Handles high pressure', 'Tested up to 3.5 MPa, well above the usual 7 to 12 bar standard.'], AQ_COPPER, ...INSTANT.slice(1, 5)],
    warranty: INSTANT_W, table: { title: 'Aquapower AQP-28N', columns: ['Model', 'Type', 'Heating element voltage', 'Heating element power (kW)', 'Weight (kg)', 'Length (mm)', 'Width (mm)', 'Height (mm)', 'Required breaker (amps)', 'Flow rate'], rows: [['AQP-28N', 'Singlepoint', '220V', '3.5', '2.35', '225', '75', '325', '20', '2 Liters/minute']], notes: [] }, from: 'product/aquapower-aqp-28n/' },
  { slug: 'aquapower-q35m', name: 'Aquapower Q35M', brand: 'Aquapower', cat: 'instant', sub: 'Singlepoint', for: ['home'], img: 'aquapower-q35m',
    short: 'A single-point heater with its own shower set, ready for one bathroom.',
    key: [['3.5', 'kW'], ['2', 'L/min to start'], ['20', 'A breaker']],
    best: ['One shower', 'Replacing an old heater', 'Condos'],
    feats: [AQ_COPPER, ...INSTANT], warranty: INSTANT_W, specs: ['Aquapower-Q35M-1'], from: 'product/aquapower-q35m/' },
  { slug: 'aquapower-q6m-q9m', name: 'Aquapower Q6M / Q9M', brand: 'Aquapower', cat: 'instant', sub: 'Multipoint', for: ['home', 'business'], img: 'aquapower-q6',
    short: 'Our most powerful instant heaters, for several taps or a strong rain shower.',
    key: [['6 / 9', 'kW'], ['2', 'L/min to start'], ['2+', 'taps']],
    best: ['Big bathrooms', 'Rain showers', 'Small shops and gyms'],
    feats: [['Power for more than one tap', 'Up to 9 kW, enough for a shower and a sink at the same time.'], AQ_COPPER, ...INSTANT.slice(0, 5)],
    warranty: INSTANT_W, specs: ['Aquapower-Q6M-and-Q9M'], from: 'product/aquapower-q6m/' },
  { slug: 'aquapower-s35m-s45m', name: 'Aquapower S35M / S45M', brand: 'Aquapower', cat: 'instant', sub: 'Singlepoint', for: ['home'], img: 'aquapower-s35',
    short: 'A compact single-point heater for one shower, in two power sizes.',
    key: [['3.5 / 4.5', 'kW'], ['1.2', 'kg'], ['2', 'L/min to start']],
    best: ['One shower', 'Condos', 'Apartments'],
    feats: [AQ_COPPER, ...INSTANT], warranty: INSTANT_W, specs: ['Aquapower-S35M-and-S45M'], from: 'product/aquapower-s35m/' },
  { slug: 'gratek-aquarius-aqa-30', name: 'Gratek Aquarius AQA-30 / AQA-55', brand: 'Gratek', cat: 'instant', sub: 'Singlepoint', for: ['home'], img: 'gratek-aquarius-shower',
    short: 'Gratek\'s own single-point heater, with a built-in pump for weak water pressure.',
    key: [['3.5 / 5.5', 'kW'], ['Pump', 'built in'], ['Steel', 'stainless tank']],
    best: ['Low water pressure', 'Upper floors', 'One shower'],
    feats: [AQ_PUMP, ['Stainless steel tank', 'Resists rust and keeps the water clean.'], ...INSTANT.slice(0, 4), INSTANT[5]],
    warranty: INSTANT_W, specs: ['AQUARIUS-AQA30-and-AQA55'], from: 'product/aquarius-aqa-30/' },
  { slug: 'gratek-aquarius-aqa-30e', name: 'Gratek Aquarius AQA-30E / AQA-55E', brand: 'Gratek', cat: 'instant', sub: 'Multipoint', for: ['home'], img: 'gratek-aquarius',
    short: 'Gratek\'s multipoint heater with a built-in pump: shower and sink from one unit.',
    key: [['3.5 / 5.5', 'kW'], ['Pump', 'built in'], ['2+', 'taps']],
    best: ['Shower and sink', 'Low water pressure', 'Family bathrooms'],
    feats: [['Serves more than one tap', 'Multipoint: one heater supplies the shower and the bathroom sink together.'], AQ_PUMP, ['Automatic relief valve', 'Lets out excess pressure on its own, for extra safety.'], ['Set it your way', 'Adjust the power, the water flow and the outlet temperature.'], ...INSTANT.slice(1, 4)],
    warranty: INSTANT_W, specs: ['AQUARIUS-AQA30E-and-AQA55E'], from: 'product/aquarius-aqp-55/' },

  // ---------- storage ----------
  { slug: 'rheem', name: 'Rheem Storage Water Heaters', brand: 'Rheem', cat: 'storage', sub: 'Wall-hung and floor-standing', for: ['home', 'business'], img: 'rheem',
    short: 'Rheem\'s glass-lined tanks keep 25 to 454 liters of hot water ready for the whole house.',
    key: [['25–454', 'liters'], ['60°C', 'preset'], ['11', 'sizes']],
    best: ['Family homes', 'Several taps at once', 'Small hotels'],
    feats: [['Glass-lined tank', 'Rheemglas enamel is fused to the steel at 870°C, so hot water can\'t corrode the tank.'], ['Safety valve and thermostat', 'A UL-approved pressure relief valve, and a thermostat that cuts the power before the water gets too hot.'], ['Long-life element', 'An Incoloy stainless element that resists dry firing and limits sediment build-up.'], ['Anode rod', 'A sacrificial anode protects the tank from corrosion for years.'], ['Keeps heat in', 'Thick CFC-free foam insulation means less power to keep the water hot.'], ['Weather resistant', 'Colorbond steel jacket with no screws on top or bottom, rated IPX1.'], ['Ready to mount', 'Comes with a sturdy bracket and masonry bolts. Meets IEC 60335-2-21.']],
    warranty: '', specs: ['Rheem-1-Specifications-', 'Rheem-2-Specifications'], from: 'product/rheem-series/' },
  { slug: 'everhot', name: 'Everhot Storage Water Heaters', brand: 'Everhot', cat: 'storage', sub: 'Floor-standing or wall-hung', for: ['home', 'business'], img: 'everhot',
    short: 'An Australian-designed tank heater in 11 sizes, from 25 liters for one bathroom to 492 for a building.',
    key: [['25–492', 'liters'], ['11', 'sizes'], ['ISO 9001', 'certified']],
    best: ['Family homes', 'Indoor or outdoor', 'Kitchens and laundries'],
    feats: [['Enamel-lined tank', 'A durable vitreous enamel lining keeps the tank from rusting.'], ['Pressure relief valve', 'Set at 0.85 MPa to protect against too much pressure. Also lets the tank be drained for servicing.'], ['Adjustable thermostat', 'Cuts the power once the water reaches your setting, saving electricity and preventing scalding.'], ['Anode rod', 'Protects the inner tank from corrosion and makes the heater last longer.'], ['Indoors or outdoors', 'Suitable for both, with CFC-free foam insulation inside an epoxy-coated steel jacket.']],
    warranty: '', specs: ['Everhot-Floor-Stand-or-Wall-Hung-Specifications', 'Everhot-Floor-Stand-Specifications'], from: 'product/everhot-eras025/' },

  // ---------- heat pumps ----------
  { slug: '5-star-integral-heat-pump', name: '5 Star Integral Heat Pump', brand: '5 Star', cat: 'heatpump', sub: 'All-in-one, 100 to 300 L', for: ['home', 'business'], img: 'heatpump-5star',
    short: 'A heat pump and hot water tank in one tall unit. Uses about a quarter of the power of an electric heater.',
    key: [['4', 'COP'], ['100–300', 'liters'], ['0.7', 'kW power use']],
    best: ['Homes with high hot water use', 'Laundry rooms', 'Small resorts'],
    feats: [['About 4 times as efficient', 'It produces 2.8 kW of heat from 0.7 kW of electricity (COP 4).'], ['Cools the room it\'s in', 'In a laundry or storage room it lowers the temperature and removes humidity while it heats water.'], ['Uses waste heat', 'Placed near a kitchen or in a garage, it reuses the warm air there.'], ['Backup heater built in', 'A 1.5 kW electric heater takes over when you need extra hot water.'], ['Works with solar', 'An optional extra coil connects it to solar panels, a boiler or another heat source.']],
    warranty: '', specs: ['5-Star-Integral-Heat-Pump-Specifications-'], from: 'product/5-star-fshw-28a-100-l/' },
  { slug: 'deron-air-to-water-heat-pump', name: 'Deron Air to Water Heat Pump', brand: 'Deron', cat: 'heatpump', sub: '3.4 to 20 kW', for: ['business'], img: 'deron-wizard',
    short: 'Commercial heat pumps that heat water to 60°C for hotels, hospitals and buildings, and can cut heating costs by up to 70%.',
    key: [['Up to 70%', 'lower heating cost'], ['60°C', 'hot water'], ['7', 'sizes']],
    best: ['Hotels and resorts', 'Hospitals', 'Condo buildings'],
    feats: [['A quarter of the running cost', 'Runs at about a quarter of the cost of an electric water heater and a third of a gas heater.'], ['Hot water at 60°C', 'Delivers water at 60°C ±5°C, and can be set up for over 65°C if your building needs it.'], ['Several compressors in one unit', 'Each with its own control and safety circuit, so running hours stay even and the machine lasts longer.'], ['Runs itself', 'Fully automatic heating, water feed and temperature control, ready 24 hours, with automatic defrost.'], ['Built for 10 to 15 years', 'Main parts come from internationally known brands.']],
    warranty: '', specs: ['Air-to-Water-Specifications'], from: 'product/deron-air-to-water-heat-pump/' },
  { slug: 'deron-water-to-water-heat-pump', name: 'Deron Water to Water Heat Pump', brand: 'Deron', cat: 'heatpump', sub: '11.5 to 40 kW', for: ['business'], img: 'deron-w2w', gallery: 'deron-w2w-range',
    short: 'Takes heat from ground, lake or river water to make hot water, and can cool at the same time.',
    key: [['4.4', 'COP'], ['11.5–40', 'kW'], ['15', 'years service life']],
    best: ['Buildings with a water source', 'Indoor plant rooms', 'Heating and cooling together'],
    feats: [['Heat from water', 'Works with ground, lake or river water, or a glycol brine loop.'], ['Very efficient', 'Up to 4.4 units of heat for every unit of electricity.'], ['Safe by design', 'Water and electrical parts are kept fully separate.'], ['Quiet enough for indoors', 'Low-noise design with sound insulation inside the case.'], ['Quality parts', 'Copeland scroll compressor, Emerson expansion valve and stainless steel plate heat exchangers.']],
    warranty: '', specs: ['Water-to-Water-Heatpump-Specifications'], from: 'product/deron-water-to-water-heat-pump/' },
  { slug: 'deron-swimming-pool-heat-pump', name: 'Deron Swimming Pool Heat Pump', brand: 'Deron', cat: 'heatpump', sub: '34 to 86 kW', for: ['business'], img: 'deron-pool',
    short: 'Keeps resort and hotel pools at a comfortable temperature, with a corrosion-proof titanium heat exchanger.',
    key: [['34–86', 'kW'], ['Titanium', 'heat exchanger'], ['5', 'sizes']],
    best: ['Resort pools', 'Hotel pools', 'Spas'],
    feats: [['Made for pool water', 'A titanium heat exchanger resists chlorine and corrosion.'], ['Quiet', 'A compressor jacket and anti-vibration pads keep the noise down.'], ['Quality parts', 'Copeland scroll compressor, Emerson expansion valve and Saginomiya 4-way valve.'], ['Can cool too', 'Also brings pool water down on very hot days.']],
    warranty: '', specs: ['Swimming-Pool-Heat-Pump-Specifications-2'], from: 'product/swimming-pool-heat-pump/' },

  // ---------- solar ----------
  { slug: '5-star-solar-water-heater', name: '5 Star CZ2.0 / CZ4.0 Solar Water Heater', brand: '5 Star', cat: 'solar', sub: '40 or 80 gallons', for: ['home', 'business'], img: 'solar-5star',
    short: 'A rooftop solar heater with a 150 or 300 liter tank, and a 2 kW electric backup for cloudy days.',
    key: [['40 / 80', 'gallons'], ['92–96%', 'sunlight absorbed'], ['<5°C', 'heat loss a day']],
    best: ['Houses with a sunny roof', 'Resorts', 'Lower power bills'],
    feats: [['Free heat from the sun', 'The black chrome coating absorbs 92 to 96% of the sunlight that reaches it.'], ['Hot water stays hot', 'Thick foam insulation: the water loses less than 5°C in 24 hours.'], ['Full water pressure', 'Works at 0.6 MPa and handles up to 1.2 MPa, so showers feel normal.'], ['Long life', 'The inner tank is lined to resist heat and corrosion.'], ['Fits most roofs', 'Several bracket styles for different roofs. Also available as a split system.']],
    warranty: '', specs: ['Solar-Water-Heater-Specifications'], from: 'product/5-star-cz2-0/' },

  // ---------- tanks ----------
  { slug: 'haase-energy-storage-tank', name: 'HAASE Energy Storage Tank', brand: 'HAASE', cat: 'tank', sub: '1,000 to 40,000 liters', for: ['business'], img: 'haase-tank', diagram: ['haase-diagram', 'How a HAASE tank connects solar, a boiler and a chiller to the building\'s showers (diagram from DPY)'],
    short: 'A German-made tank that stores heat, not just water, and delivers clean hot water to a whole building.',
    key: [['1,000–40,000', 'liters'], ['93%', 'storage efficiency'], ['Germany', 'made in']],
    best: ['Hotels and hospitals', 'Several heat sources', 'Tight plant rooms'],
    feats: [['Clean water, every time', 'Domestic water runs only through stainless steel coils, first in and first out, so sludge, rust and bacteria can\'t build up.'], ['Less heat lost', 'About 93% storage efficiency, compared with about 70% for a steel pressure tank.'], ['Connects many heat sources', 'Heat pumps, solar, boilers or waste heat can all feed the same tank.'], ['Built where it\'s needed', 'Comes in modules that are assembled on site, so it fits rooms a single tank can\'t enter.'], ['Pressure without a pressure tank', 'The tank itself is unpressurised, but the hot water comes out at full pressure.']],
    warranty: '', specs: [], from: 'product/haase-hot-water-energy-tank/' },
  { slug: 'champion-storage-tank', name: 'Champion Glass-Lined Storage Tank', brand: 'Champion', cat: 'tank', sub: '350 to 2,000 gallons', for: ['business'], img: 'champion-tank',
    short: 'Custom hot water storage tanks with a tough blue glass lining, for buildings that use a lot of hot water.',
    key: [['350–2,000', 'gallons'], ['125 PSI', 'standard rating'], ['220°C', 'design temperature']],
    best: ['Hotels', 'Hospitals', 'Factories'],
    feats: [['Tough glass lining', 'A 2 mm acid-resistant blue glass lining resists abrasion, chemicals and knocks. Widely used for drinking water.'], ['Rated for pressure', '125 PSI as standard, 150 PSI available, and tested at 300 PSI.'], ['Holds heat', '50 mm of high-density fiberglass wool under an aluminum jacket.'], ['Everything included', 'Magnesium anode rod, pressure and temperature relief valve, pressure and temperature gauges, manhole, drain, lifting lugs and three support legs.']],
    warranty: '', specs: ['CHAMPION-STORAGE-TANK-SPECS'], from: 'product/champion-storage-tank/' },
  { slug: 'enermax-storage-tank', name: 'Enermax Smart Hot Water Storage Tank', brand: 'Enermax', cat: 'tank', sub: 'Heat exchanger tank', for: ['business'], img: 'enermax-web', photo: true,
    short: 'A storage and heat exchange tank that takes heat from several sources and serves several uses.',
    key: [['Multiple', 'heat sources'], ['Multiple', 'hot water uses'], ['Storage', 'and heat exchange']],
    best: ['Solar plus heat pump systems', 'Hotels', 'Buildings'],
    feats: [['Several heat sources', 'Solar, heat pumps and boilers can all heat the same tank.'], ['Several uses', 'One tank can supply showers, kitchens and other hot water needs.']],
    warranty: '', specs: [], from: 'product/rotex-sanicube-storage-heat-exchanger-she-tank/' },
  { slug: 'rotex-sanicube', name: 'Rotex Sanicube Heat Exchanger Tank', brand: 'Rotex', cat: 'tank', sub: 'German made', for: ['business'], img: '',
    short: 'A hygienic German tank that heats water as it passes through stainless coils, so no water sits and goes stale.',
    key: [['50 years', 'engineering life'], ['316', 'stainless coils'], ['Germany', 'made in']],
    best: ['Hospitals', 'Hotels', 'Large systems'],
    feats: [['Hygienic hot water', 'Water is heated as it flows through stainless steel coils, so legionella can\'t grow. Tested by the Institute of Hygiene in Tübingen.'], ['No corrosion', 'Polypropylene inside and out: it can\'t rust and needs almost no maintenance.'], ['Little scale', 'Corrugated 316 stainless steel coils transfer heat fast with minimal scaling.'], ['Modular', 'Several tanks can be linked, so hot water keeps flowing even while one is serviced.'], ['Works with solar', 'Solar or waste heat can be added at any time.']],
    warranty: '', specs: [], from: 'product/rotex-sanicube-storage-heat-exchanger-she-tank/' },

  // ---------- pumps, pipes, control, fans ----------
  { slug: 'wilo-pumps', name: 'Wilo Pumps', brand: 'Wilo', cat: 'pump', sub: 'Circulation and booster pumps', for: ['business'], img: 'wilo-pump',
    short: 'Premium German pumps for building services, water supply and industry.',
    key: [['Circulation', 'pumps'], ['Booster', 'sets'], ['Germany', 'brand']],
    best: ['Hot water circulation', 'Water pressure boosting', 'Plant rooms'],
    feats: [['Hot water at every tap', 'Circulation pumps keep hot water moving through the pipes, so no one waits for it to run hot.'], ['Steady pressure', 'Booster sets keep the pressure even on every floor.'], ['Sized by our engineers', 'We pick the pump to match your building and your heaters.']],
    warranty: '', specs: [], from: 'product/wilo-pump/' },
  { slug: 'aquaplast-ppr-pipes', name: 'Aquaplast PPR Pipes & Fittings', brand: 'Aquaplast', cat: 'pipe', sub: 'Pipes, elbows and valves', for: ['home', 'business'], img: 'aquaplast',
    short: 'Heat-resistant PPR pipes, elbows and valves for hot water lines.',
    key: [['PPR', 'heat resistant'], ['Pipes', 'and fittings'], ['Valves', 'included']],
    best: ['New hot water lines', 'Replacing old pipes', 'Whole buildings'],
    feats: [['Made for hot water', 'PPR pipes handle hot water without rusting or scaling.'], ['Complete set', 'Pipes, elbows, couplings and valves from one supplier, installed by our team.']],
    warranty: '', specs: [], from: 'product/ppr-pipes-and-fittings/' },
  { slug: 'my-pv-ac-thor-9s', name: 'my-PV AC·THOR 9s', brand: 'my-PV', cat: 'control', sub: 'Up to 9 kW, 1 to 3 phase', for: ['home', 'business'], img: 'acthor-9s',
    short: 'Sends spare power from your solar panels into your water heater, instead of exporting it.',
    key: [['3 × 3,000', 'W output'], ['1–3', 'phase'], ['20-0300', 'item no.']],
    best: ['Homes with solar panels', 'Bigger solar systems', 'Three-phase buildings'],
    feats: [['Hot water from spare solar power', 'It measures your surplus and feeds exactly that much into the heating element, smoothly from zero up.'], ['For any supply', 'Single, two or three phase, with three outputs of 3,000 W plus a 16 A relay.'], ['Ready to install', 'Comes with cable connectors and a digital temperature sensor on a 5 m cable.']],
    warranty: '', specs: [], from: 'product/my-pv-ac%c2%b7thor-9s-9kw/' },
  { slug: 'my-pv-ac-thor-i', name: 'my-PV AC·THORi', brand: 'my-PV', cat: 'control', sub: 'Single phase', for: ['home'], img: 'acthor-i',
    short: 'The single-phase AC·THOR for homes: uses spare solar power to heat water.',
    key: [['0–3', 'kW output'], ['1', 'phase'], ['20-0103', 'item no.']],
    best: ['Homes with solar panels', 'Single-phase supply'],
    feats: [['Hot water from spare solar power', 'Feeds your surplus solar power into the water heater, smoothly from 0 to 3 kW, plus a 16 A relay.'], ['Ready to install', 'Comes with a stylus, wall bracket and fixings, a plug-in output and a digital temperature sensor on a 5 m cable.']],
    warranty: '', specs: [], from: 'product/my-pv-ac%c2%b7thori-6kw/' },
  { slug: 'my-pv-power-meter', name: 'my-PV Power Meter', brand: 'my-PV', cat: 'control', sub: '3-phase meter', for: ['home', 'business'], img: 'power-meter',
    short: 'Measures your solar surplus so the AC·THOR knows how much power it can use.',
    key: [['3', 'phase'], ['3 × 60 A', 'clamps'], ['20-0102', 'item no.']],
    best: ['AC·THOR systems', 'Three-phase supply'],
    feats: [['Clip-on measuring', 'Comes with three clamp-on current sensors (60 A, 10 mm²). No rewiring of your cables.']],
    warranty: '', specs: [], from: 'product/my-pv-power-meter/' },
  { slug: 'katen-exhaust-fans', name: 'Katen Exhaust Fans', brand: 'Katen', cat: 'fan', sub: 'Wall and window fans', for: ['home'], img: 'katen-fan', gallery: 'katen-range',
    short: 'Exhaust fans that clear steam from the bathroom and heat from the kitchen.',
    key: [['3', 'models'], ['Wall', 'or window'], ['Gratek', 'carries it']],
    best: ['Bathrooms', 'Kitchens', 'Laundry rooms'],
    feats: [['Less steam, less mold', 'Pulls moist air out after a hot shower.'], ['Three models', 'BPT12-13A, VL-LA and VF-AK, for walls and windows.']],
    warranty: '', specs: [], from: 'product/exaust-fan/' },
]
